# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Yelp Review App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yelp Review App

  target 'Yelp Review AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Yelp Review AppUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'
pod 'Kingfisher', '~> 7.0'

end
